feat: add IdempotencyKey to prevent double payments
cutters-digital/gateway-protobuf pull request #3
Opened 2024-09-25 12:44 UTC by michelemendel

2024-09-25 14:11 UTC, anthomm commented
Please review [this](https://protobuf.dev/programming-guides/style/) style guide for protobuf.

2024-09-25 14:14 UTC, anthomm requested changes

2024-09-25 14:14 UTC, anthomm commented on proto/server/cutters_api.proto
> +  string IdempotencyKey = 7;
Please use the protocol buffer conventions for naming fields.

2024-09-25 14:14 UTC, anthomm commented on proto/server/cutters_api.proto
> +  string IdempotencyKey = 3;
Please use the protocol buffer conventions for naming fields.

2024-09-26 05:47 UTC, michelemendel commented on proto/server/cutters_api.proto
> +  string IdempotencyKey = 7;
fixed

2024-09-26 05:47 UTC, michelemendel commented on proto/server/cutters_api.proto
> +  string IdempotencyKey = 3;
fixed

2024-09-26 07:57 UTC, anthomm approved these changes
LGTM

2024-09-26 08:59 UTC, merged